config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/new'
  get 'posts/show'
  get '/profiles/:username/followers', to: 'profile#followers', as: 'profile_followers'
  get '/profiles/:username/following', to: 'profile#following', as: 'profile_following'
  get '/profiles/search', to: 'profile#search', as: 'profile_search'
  get '/profiles/:username', to: 'profile#show', as: 'profile_show'
  get 'accounts/new'
  get 'accounts/create'
  get 'accounts/update'
  get 'home/index'

  devise_for :accounts, controllers: {
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions'
  }

  resources :posts, only: [:new, :create, :index, :show]

  resources :follows, only: [:create, :destroy]
  
  


  post 'follow/:id' => 'follows#follow', as: 'follow_account'
  delete 'follow/:id' => 'follows#unfollow', as: 'unfollow_account'
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  root to: "home#index"

  devise_scope :account do
    get '/accounts/sign_out', to: 'accounts/sessions#destroy'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  has_one_attached :image
  has_many :likes
  has_many :comments, dependent: :destroy

  def likes_count
    likes.count
  end

  def comments_count
    comments.count
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:index]

  def index
    following_ids = current_account.following.pluck(:id)
    @posts_following = Post.where(account_id: following_ids).order(created_at: :desc)
    @posts_not_following = Post.where.not(account_id: following_ids).order(created_at: :desc)
    @comment = Comment.new
  end
  
  

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end
  

  def create
    @post = current_account.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: 'Post created successfully'
    else
      flash[:error] = 'Unable to create post.'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:description, :image)
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/index.html.erb
<div class="posts-wrapper justify-content-center">
  <div class="row mt-1 text-center ">
    <% if @posts_following.present? %>
      <p class="text-center">Recent posts by users you follow</p>
    <% else %>
      <p class="text-center">You are not following anyone.</p>
    <% end %>
  </div>

  <% @posts_following.first(5).each do |post| %>
    <div style="max-width: 450px;" class="card my-3 mx-auto text-center text-dark">
      <div class="card-body">
        <div class="row my-1">
          <div class="col-2">
            <% if post.account.profile_image.attached? %>
              <%= image_tag post.account.profile_image, class: "rounded-circle", style: "max-height: 50px; max-width: 50px;" %>
            <% end %>
          </div>
          <div class="col-10">
            <p>
              <span>
                <%= link_to "@#{post.account.username}", profile_show_path(username: post.account.username), class: "text-decoration-none" %>
                on <%= post.created_at.strftime('%B %d, %Y') %>
              </span>
            </p>
          </div>
        </div>

        <% if post && post.image.attached? %>
          <div class="row">
            <%= image_tag post.image, class: "card-img-top", style: "max-height: 250px; max-width: 450px;" %>
          </div>
        <% end %>

        <br>

        <div class="row">
          <div class="col-6">
            <% if current_account && (like = post.likes.find_by(account: current_account)) %>
              <%= button_to "Unlike", post_like_path(post, like), method: :delete, class: "btn btn-danger" %>
            <% else %>
              <%= button_to "Like", post_likes_path(post), method: :post, class: "btn btn-primary" %>
            <% end %>
          </div>
          <div class="col-6">
            <p><strong>Total Likes:</strong> <%= post.likes_count %></p>
          </div>
        </div>

        <div class="row">
          <p class="card-title mt-1"><%= post.description %></p>
        </div>

        <div class="row mt-1">
          <div class="col-12">
            <p><strong>Total Comments:</strong> <%= post.comments_count %></p>
          </div>
        </div>

        <div class="row mt-1">
          <% post.comments.first(5).each do |comment| %>
            <div class="row mb-1 comment-section post-<%= post.id %>">
              <p class="card-text col-4">
                <%= link_to "@#{comment.account.username}", profile_show_path(username: comment.account.username), class: "text-decoration-none" %>
              </p>
              <p class="card-text col-8"><%= comment.body %></p>
            </div>
          <% end %>
        </div>

        <div class="row">
          <%= link_to "View Full Post", post_path(post) %>
        </div>
      </div>
    </div>
  <% end %>

  <hr class="hr" />


<div class="row mt-1 text-center">
<p class="text-center">Suggested Posts</p>
</div>
  <% @posts_not_following.each do |post| %>
    <div style="max-width: 450px;" class="card my-3 mx-auto text-center text-dark">
      <div class="card-body">
        <div class="row my-1">
          <div class="col-2 ">
             <% if post.account.profile_image.attached? %>
            <%= image_tag post.account.profile_image, class: "rounded-circle", style: "max-height: 50px; max-width: 50px;" %>
          <% end %>
          </div>
          <div class="col-10">
            <p><span> <%= link_to "@#{post.account.username}", profile_show_path(username: post.account.username), class: "text-decoration-none" %> on <%= post.created_at.strftime('%B %d, %Y') %> </span></p>
          </div>
        </div>
        <% if post && post.image.attached? %>
          <div class="row">
            <%= image_tag post.image, class: "card-img-top", style: "max-height: 250px; max-width: 450px;" %>
          </div>
        <% end %>
        <br>
        <div class="row">
            <div class="col-12">
              <p><strong>Total Likes:</strong> <%= post.likes_count %></p>
            </div>
          </div>
        <div class="row">
          <p class="card-title mt-1"><%= post.description %></p>
          
        </div>

<div class="row mt-1">
    <div class="col-12">
            <p><strong>Total Comments:</strong> <%= post.comments_count %></p>
            </div>
  </div>

          <div class="row mt-1">
            <% post.comments.first(2).each do |comment| %>
              <div class="row mb-1 comment-section post-<%= post.id %>">
                <p class="card-text col-4"><%= link_to "@#{comment.account.username}", profile_show_path(username: comment.account.username), class: "text-decoration-none" %></p>
                 <p class="card-text col-8"><%= comment.body %></p>
              </div>
            <% end %>
          </div>
          <div class="row">
            <%= link_to "View Full Post", post_path(post) %>
          </div>
        </div>
</div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
  <% if flash[:error] %>
    <div class="alert alert-danger"><%= flash[:error] %></div>
  <% end %>

  <%= form_for(@post, url: posts_path, html: {multipart: true}) do |f| %>
    <div class="mb-3">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_field :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :image, class: "form-label" %>
      <%= f.file_field :image, class: "form-control", required: true %>
    </div>

    <div class="mb-3">
      <%= f.submit "Create Post", class: "btn btn-primary" %>
      <%= link_to "Cancel", root_path, class: "btn btn-secondary" %>
    </div>
  <% end %>

app/views/posts/show.html.erb
<div class="posts-wrapper d-flex justify-content-center text-dark">
<div style="max-width: 450px;" class="card my-3">
      <div class="card-body">
         <div class="row">
          <div class="col-2"> 
            <% if @post.account.profile_image.attached? %>
            <%= image_tag @post.account.profile_image, class: "rounded-circle", style: "max-height: 50px; max-width: 50px;" %>
          <% end %>
          </div>
          <div class="col-10">
            <p><span> <%= link_to "@#{@post.account.username}", profile_show_path(username: @post.account.username), class: "text-decoration-none" %> on <%= @post.created_at.strftime('%B %d, %Y') %> </span></p>
          </div>
        </div>
         <% if @post && @post.image.attached? %>
          <div class="row">
            <%= image_tag @post.image, class: "card-img-top", style: "max-height: 250px; max-width: 450px;" %>
          </div>
        <% end %>
        <div class="col">
          <div class="row">
            <p class="card-title mt-3"> <%= @post.description %></p>
          </div>
          <div class="row">
            <div class="col-6">
              <% if current_account && (like = @post.likes.find_by(account: current_account)) %>
                <%= button_to "Unlike", post_like_path(@post, like), method: :delete, class: "btn btn-danger" %>
              <% else %>
                <%= button_to "Like", post_likes_path(@post), method: :post, class: "btn btn-primary" %>
              <% end %>
            </div>
            <div class="col-6">
              <p><strong>Total Likes:</strong> <%= @post.likes_count %></p>
            </div>
          </div>
         
<div class="row mt-2">
         <%= form_with(model: [ @post, Comment.new ], local: true, class: "w-100") do |form| %>
    <div class="form-group d-flex">
      <%= form.text_field :body, class: "form-control mr-2", rows: 1, placeholder: "Leave a comment", required: true %>
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
  </div>
   <div class="row mt-2">
            <div class="col-9">
            <p><strong>Total Comments:</strong> <%= @post.comments_count %></p>
            </div>
             <div class="col-3">
            <%= link_to "Back", :back, class: "btn btn-secondary" %>
            </div>
        </div>
          <div class="row mt-2">
  <% @post.comments.each do |comment| %>
    <div class="mt-1 row comment-section post-<%= @post.id %>">
        <p class="card-text col-4"><%= link_to "@#{comment.account.username}", profile_show_path(username: comment.account.username), class: "text-decoration-none" %></p>
        <p class="card-text col-8"><%= comment.body %></p>
    </div>
  <% end %>
</div>

          
        </div>
      </div>
    </div>
    </div>

app/views/posts/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();