config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/new'
  get 'posts/show'
  get '/profiles/:username/followers', to: 'profile#followers', as: 'profile_followers'
  get '/profiles/:username/following', to: 'profile#following', as: 'profile_following'
  get '/profiles/search', to: 'profile#search', as: 'profile_search'
  get '/profiles/:username', to: 'profile#show', as: 'profile_show'
  get 'accounts/new'
  get 'accounts/create'
  get 'accounts/update'
  get 'home/index'

  devise_for :accounts, controllers: {
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions'
  }

  resources :posts, only: [:new, :create, :index, :show]

  resources :follows, only: [:create, :destroy]
  
  


  post 'follow/:id' => 'follows#follow', as: 'follow_account'
  delete 'follow/:id' => 'follows#unfollow', as: 'unfollow_account'
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  root to: "home#index"

  devise_scope :account do
    get '/accounts/sign_out', to: 'accounts/sessions#destroy'
  end
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  validates :username, uniqueness: true

  


  # Relationships
  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: "followee_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :followee
  has_many :followers, through: :passive_follows, source: :follower

  def following?(other_account)
    self.following.include?(other_account)
  end

  def followers_count
    followers.count
  end

  def following_count
    following.count
  end

  def sign_up_params
    params.require(:account).permit(:username, :first_name, :last_name, :bio, :profile_image, :email, :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:account).permit(:username, :first_name, :last_name, :bio, :profile_image, :email, :password, :password_confirmation, :current_password)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :account
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: "Account"
    belongs_to :followee, class_name: "Account"
  end
  

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :account
  belongs_to :post


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  has_one_attached :image
  has_many :likes
  has_many :comments, dependent: :destroy

  def likes_count
    likes.count
  end

  def comments_count
    comments.count
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    def follow
        followee = Account.find_by(username: params[:username])
        current_account.following << followee
        redirect_to profile_show_path(followee.username)
      end
    
      def unfollow
        followee = Account.find_by(username: params[:username])
        current_account.active_follows.find_by(followee_id: followee.id).destroy
        redirect_to profile_show_path(followee.username)
      end
end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    include Turbo::StreamsHelper

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create(account: current_account)

    respond_to do |format|
        format.turbo_stream
      end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = @post.likes.find(params[:id])
    @like.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:index]

  def index
    following_ids = current_account.following.pluck(:id)
    @posts_following = Post.where(account_id: following_ids).order(created_at: :desc)
    @posts_not_following = Post.where.not(account_id: following_ids).order(created_at: :desc)
    @comment = Comment.new
  end
  
  

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end
  

  def create
    @post = current_account.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: 'Post created successfully'
    else
      flash[:error] = 'Unable to create post.'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:description, :image)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_account!

  def show
    @account = Account.find_by(username: params[:username])
    @posts = @account.posts.order(created_at: :desc) if @account
    if @account.username.nil?
      # handle the case when the account does not have a username
      # you can redirect to an error page or display a default username
      @username = "Unknown user"
    else
      @username = @account.username
    end
  end
  
  def search
    @query = params[:q]
    @accounts = Account.where("username LIKE ?", "%#{@query}%")
  end


  def edit
    @account = current_account
  end

  def update
    @account = current_account
    if @account.update(account_params)
      flash[:success] = "Profile updated successfully"
      redirect_to profile_path(@account)
    else
      render 'edit'
    end
  end

  def follow
    followee = Account.find_by(username: params[:username])
    current_account.following << followee
    redirect_to profile_show_path(followee.username)
  end

  def unfollow
    followee = Account.find_by(username: params[:username])
    current_account.active_follows.find_by(followee_id: followee.id).destroy
    redirect_to profile_show_path(followee.username)
    
  end

  def followers
    account = Account.find_by(username: params[:username])
    @followers = account.followers
  end

  def following
    account = Account.find_by(username: params[:username])
    @following = account.following
  end
  

  private

  def account_params
    params.require(:account).permit(:accountname, :first_name, :last_name, :bio, :profile_image)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubySocial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-dark text-white">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <% if account_signed_in? %>
      <%= link_to "RubySocial", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
            <%= link_to "Dashboard", posts_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Profile", profile_show_path(username: current_account.username), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Post", new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= form_tag profile_search_path, method: :get, class: "d-flex" do %>
              <%= text_field_tag :q, params[:q], placeholder: "Search for user", class: "form-control me-2" %>
              <%= submit_tag "Search", class: "btn btn-outline-primary" %>
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Logout", destroy_account_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>
    <% else %>
      <%= link_to "RubySocial", root_path, class: "navbar-brand" %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Login", new_account_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_account_registration_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav> 


    <div class="container mt-3">
 
      <%= yield %>
    </div>
     <div class="push"></div>
  </body>

<!-- Footer -->
<footer class="text-center text-lg-start bg-secondary mt-4 fixed-bottom" style="padding: 0px; font-size: 0.8rem;">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-2">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-6 col-lg-6 col-xl-5 mx-auto mb-4">
          <!-- Content -->
          <h6 class="fw-bold mb-4">
            ABOUT
          </h6>
          <p>
            Hello I am Pierce Connaughton and this is my first Ruby On Rails web-app. 
            The web-app allows you to create posts, that other users can like and comment on.
            You can also choose to follow other users on the site displaying there posts on your feed first.
            I used PostgreSQL for the database and Action Storage to store the images that the users upload.
          </p>
        </div>

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Quick links
          </h6>
          <% if account_signed_in? %>
          <p>
            <%= link_to "Dashboard", posts_index_path, class: "text-light" %>
          </p>
           <p>
            <%= link_to "My Profile", profile_show_path(username: current_account.username), class: "text-light" %>
          </p>
          <p>
            <%= link_to "New Post", new_post_path, class: "text-light" %>
          </p>
           <p>
            <%= link_to "Logout", destroy_account_session_path, method: :delete, class: "text-light" %>
          </p>
         


          <% else %>
          <p>
             <%= link_to "Login", new_account_session_path, class: "text-light" %>
          </p>
           <p>
             <%= link_to "Signup", new_account_registration_path, class: "text-light" %>
          </p>
          <%end%>
          
         
        </div>

       



        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-2 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fa fa-map-marker"></i>&nbsp; Sligo Town, Co.Sligo, Republic Of Ireland.</p>
          <p>
            <i class="fa fa-envelope"></i>&nbsp; <a href="mailto:ti436522@gmail.com" target="_blank"
              class="text-light">ti436522@gmail.com</a>
          </p>
          <p><i class="fa fa-phone"></i>&nbsp; +353 083-074-7786</p>

        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.05);">
    &copy; 2023 Copyright: <a href="https://pierce-connaughton.ie/" class="text-white">Pierce Connaughton</a> All rights reserved
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</html>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>